# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20170813_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencespeaker',
            name='first_time',
            field=models.BooleanField(default=False, help_text='Check this field if this is your first time speaking at a technical conference.', verbose_name='First-time speaker?'),
        ),
        migrations.AlterField(
            model_name='conferencespeaker',
            name='lodging_assistance',
            field=models.BooleanField(default=False, help_text='Check this field if you require lodging assistance in Petaluma, California during North Bay Python.', verbose_name='Lodging assistance required?'),
        ),
        migrations.AlterField(
            model_name='conferencespeaker',
            name='travel_assistance',
            field=models.BooleanField(default=False, help_text='Check this field if you require travel assistance to get to North Bay Python in Petaluma, California.', verbose_name='Travel assistance required?'),
        ),
    ]
