# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_auto_20170917_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencespeaker',
            name='code_of_conduct',
            field=models.BooleanField(default=False, help_text="I have read and, in the event that my proposal is accepted, agree that I will comply with the <a href='/code-of-conduct'>Code of Conduct</a>."),
        ),
    ]
