# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20170917_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencespeaker',
            name='reviewer',
            field=models.EmailField(blank=True, help_text='Include the e-mail address of someone who can watch a video of your talk, shortly after the video is produced, to ensure quality.', max_length=254, null=True, verbose_name='E-mail of video reviewer'),
        ),
    ]
