# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0003_merge_20170814_2247'),
        ('proposals', '0006_conferencespeaker_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialProposal',
            fields=[
                ('proposalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='symposion_proposals.ProposalBase')),
                ('extra_av', models.TextField(blank=True, help_text='We will provide you with a projector with HDMI connection, an audio connection, and one microphone per speaker. If you need anything more than this to present this talk, please list them here.', verbose_name='Extra tech and A/V requirements')),
                ('new_presentation', models.BooleanField(default=False, help_text='Check this box if PyOhio will be the first time this talk is presented at a technical conference.', verbose_name='This is a new presentation')),
                ('slides_release', models.BooleanField(default=True, help_text='I authorize PyOhio to release a copy of my slides and related materials under the Creative Commons Attribution-ShareAlike 3.0 United States licence, and certify that I have the authority to do so.')),
                ('recording_release', models.BooleanField(default=True, help_text='I authorize PyOhio to release a recording of my talk under the Creative Commons Attribution-ShareAlike 3.0 United States licence.')),
                ('prerequisite_setup', models.TextField(blank=True, help_text='Many tutorials require specific setup or installed software. Please explain your tutrial setup requirements ', verbose_name='Prerequisites tutorial participants should complete')),
                ('prerequisite_setup_html', models.TextField(blank=True)),
                ('participant_limit', models.IntegerField(blank=True, help_text='The maximum number of tutorial participants you feel comfortable accepting to your tutorial', verbose_name='The maximum number of tutorial participants')),
            ],
            options={
                'verbose_name': 'tutorial proposal',
            },
            bases=('symposion_proposals.proposalbase',),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='extended_presentation',
            field=models.BooleanField(default=False, help_text='Most talks at PyOhio go for 30 minutes. We have some openings for 45-minute talks. If you check this field, please explain in your additional notes how you would use the extra 15 minutes.', verbose_name='Optionally consider this proposal for a 45-minute slot'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='new_presentation',
            field=models.BooleanField(default=False, help_text='Check this box if PyOhio will be the first time this talk is presented at a technical conference.', verbose_name='This is a new presentation'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='recording_release',
            field=models.BooleanField(default=True, help_text='I authorize PyOhio to release a recording of my talk under the Creative Commons Attribution-ShareAlike 3.0 United States licence.'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='slides_release',
            field=models.BooleanField(default=True, help_text='I authorize PyOhio to release a copy of my slides and related materials under the Creative Commons Attribution-ShareAlike 3.0 United States licence, and certify that I have the authority to do so.'),
        ),
    ]
