# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_auto_20180209_0631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talkproposal',
            options={'permissions': (('can_manage_talks', 'Can manage talks'), ('can_review_talks', 'Can review talks')), 'verbose_name': 'talk proposal'},
        ),
        migrations.AlterModelOptions(
            name='tutorialproposal',
            options={'permissions': (('can_manage_tutorials', 'Can manage tutorials'), ('can_review_tutorials', 'Can review tutorials')), 'verbose_name': 'tutorial proposal'},
        ),
    ]
