# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_auto_20180215_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialproposal',
            name='participant_limit',
        ),
    ]
