# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_remove_tutorialproposal_participant_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talkproposal',
            options={'verbose_name': 'talk proposal'},
        ),
        migrations.AlterModelOptions(
            name='tutorialproposal',
            options={'verbose_name': 'tutorial proposal'},
        ),
    ]
