# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_auto_20180215_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencespeaker',
            name='experience',
            field=models.TextField(blank=True, help_text="List any past speaking experience you have. This can include user groups, meetups, or presentations at work or school.  Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/'>Markdown</a>.", verbose_name='Past speaking experience'),
        ),
        migrations.AlterField(
            model_name='conferencespeaker',
            name='reviewer',
            field=models.EmailField(blank=True, help_text="Email address of someone, not yourself, that will <a href='https://github.com/CarlFK/veyepar/wiki/Reviewer'>review the video of your talk</a> to make sure it is ready to publish", max_length=254, null=True, verbose_name='Email of video reviewer'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='prerequisite_setup',
            field=models.TextField(blank=True, help_text='Many tutorials require specific setup or installed software. Please explain your tutorial setup requirements.', verbose_name='Prerequisites tutorial participants should complete'),
        ),
    ]
