# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-08 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_auto_20180408_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencespeaker',
            name='pronouns',
            field=models.CharField(blank=True, help_text='Enter your pronouns to help the session chair introduce you properly.', max_length=64, null=True, verbose_name='Pronouns'),
        ),
    ]
