# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_conferencespeaker_pronouns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSpeakerOrganizerRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Role Title')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Order')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='conferencespeakerorganizerroles',
            name='roles',
            field=models.ManyToManyField(to='proposals.OrganizerRole', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='conferencespeakerorganizerroles',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.ConferenceSpeaker', verbose_name='Speaker'),
        ),
    ]
