# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_auto_20190608_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferencespeakerorganizerroles',
            options={'ordering': ['speaker'], 'verbose_name': 'Speaker Organizer Roles', 'verbose_name_plural': 'Speaker Organizer Roles'},
        ),
        migrations.AddField(
            model_name='conferencespeaker',
            name='mastodon_username',
            field=models.CharField(blank=True, help_text='Your Mastodon username (@username@instance.domain)', max_length=64),
        ),
        migrations.AddField(
            model_name='conferencespeaker',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal website URL'),
        ),
        migrations.AlterField(
            model_name='conferencespeaker',
            name='twitter_username',
            field=models.CharField(blank=True, help_text='Your Twitter username (without the @)', max_length=16),
        ),
    ]
