# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrasion', '0011_auto_20160401_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeProfile',
            fields=[
                ('attendeeprofilebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registrasion.AttendeeProfileBase')),
                ('name', models.CharField(help_text=b"Your name, as you'd like it to appear on your badge. ", max_length=64, verbose_name=b'Your name (for your conference nametag)')),
                ('company', models.CharField(blank=True, help_text=b"The name of your company, as you'd like it on your badge", max_length=64)),
                ('free_text_1', models.CharField(blank=True, help_text=b"A line of free text that will appear on your badge. Use this for your Twitter handle, IRC nick, your preferred pronouns or anything else you'd like people to see on your badge.", max_length=64, verbose_name=b'Free text line 1')),
                ('free_text_2', models.CharField(blank=True, max_length=64, verbose_name=b'Free text line 2')),
                ('name_per_invoice', models.CharField(blank=True, help_text=b"If your legal name is different to the name on your badge, fill this in, and we'll put it on your invoice. Otherwise, leave it blank.", max_length=64, verbose_name=b'Your legal name (for invoicing purposes)')),
                ('of_legal_age', models.BooleanField(default=False, verbose_name=b'18+?')),
                ('dietary_requirements', models.CharField(blank=True, max_length=256)),
                ('accessibility_requirements', models.CharField(blank=True, max_length=256)),
                ('gender', models.CharField(blank=True, max_length=64)),
            ],
            bases=('registrasion.attendeeprofilebase',),
        ),
    ]
