# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-05 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinaxcon_registrasion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='db_defined_values',
            field=models.ManyToManyField(to='pinaxcon_registrasion.DynamicValues'),
        ),
    ]
