# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrasion', '0013_auto_20160406_2228_squashed_0015_auto_20160406_1942'),
        ('pinaxcon_registrasion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoPayment',
            fields=[
                ('paymentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registrasion.PaymentBase')),
            ],
            bases=('registrasion.paymentbase',),
        ),
    ]
