# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinaxcon_registrasion', '0002_auto_20161005_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendeeprofile',
            name='db_defined_values',
        ),
        migrations.RemoveField(
            model_name='attendeeprofile',
            name='dietary_requirements',
        ),
        migrations.RemoveField(
            model_name='attendeeprofile',
            name='free_text_1',
        ),
        migrations.RemoveField(
            model_name='attendeeprofile',
            name='free_text_2',
        ),
        migrations.RemoveField(
            model_name='attendeeprofile',
            name='of_legal_age',
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='address_line_1',
            field=models.CharField(blank=True, help_text=b'This address, if provided, will appear on your receipt.', max_length=1024, verbose_name=b'Address line 1'),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=1024, verbose_name=b'Address line 2'),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=1024, verbose_name=b'Postal/Zip code'),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='address_suburb',
            field=models.CharField(blank=True, max_length=1024, verbose_name=b'City/Town/Suburb'),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='country',
            field=django_countries.fields.CountryField(default=b'US', max_length=2),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='dietary_restrictions',
            field=models.CharField(blank=True, max_length=256, verbose_name=b'Food allergies, intolerances, or dietary restrictions'),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='newsletter',
            field=models.BooleanField(default=False, help_text=b'Select to be subscribed to the low-volume North Bay Python announcements newsletter', verbose_name=b'Subscribe to North Bay Python newsletter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='state',
            field=models.CharField(blank=True, max_length=256, verbose_name=b'State/Territory/Province'),
        ),
        migrations.AlterField(
            model_name='attendeeprofile',
            name='accessibility_requirements',
            field=models.CharField(blank=True, max_length=256, verbose_name=b'Accessibility-related requirements'),
        ),
        migrations.AlterField(
            model_name='attendeeprofile',
            name='company',
            field=models.CharField(blank=True, help_text=b"The name of your company, as you'd like it on your badge and receipt", max_length=64),
        ),
        migrations.AlterField(
            model_name='attendeeprofile',
            name='gender',
            field=models.CharField(blank=True, help_text=b'Gender data will only be used for demographic purposes.', max_length=64),
        ),
        migrations.AlterField(
            model_name='attendeeprofile',
            name='name_per_invoice',
            field=models.CharField(blank=True, help_text=b"If your legal name is different to the name on your badge, fill this in, and we'll put it on your receipt. Otherwise, leave it blank.", max_length=256, verbose_name=b'Your legal name (for your receipt)'),
        ),
        migrations.DeleteModel(
            name='DemoPayment',
        ),
        migrations.DeleteModel(
            name='DynamicValues',
        ),
    ]
