# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinaxcon_registrasion', '0003_auto_20171002_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeprofile',
            name='agreement',
            field=models.BooleanField(default=False, help_text=b"I agree to act according to the conference <a href='/code-of-conduct'>Code of Conduct</a>. I also agree with the North Bay Python <a href='/terms'>Terms and Conditions</a>.", verbose_name=b'Agreement'),
        ),
    ]
